[DISPLAY]
WIDTH = 1200
HEIGHT = 800
FOREGROUND =  [255, 255, 255]
BACKGROUND =  [0, 0, 0]
FONTSIZE = 16

[FRACTAL]
DELAY = 0
LOW_ITERATIONS = 2
HIGH_ITERATIONS = 6
SIDES = 3  # This value should not be changed
SIZE = 500
RANDOM = 1
RANDOM_FACTOR = 0.16